# Generated by Django 5.1.3 on 2026-02-20 10:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon')),
                ('postal', models.CharField(max_length=5, verbose_name='PLZ')),
                ('city', models.CharField(default='Nürnberg', max_length=50, verbose_name='Ort')),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
                ('str_no', models.CharField(max_length=20, verbose_name='Nr.')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hersteller')),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Nummer')),
                ('name', models.CharField(max_length=100)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Normalpreis')),
                ('ebike_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='E-Bike-Preis')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Servicekategorie',
                'verbose_name_plural': 'Servicekategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('postal', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('str_no', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('bike_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bike_model', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.customer')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='werkstatt.invoice')),
            ],
            options={
                'verbose_name': 'Rechnungsservice',
                'verbose_name_plural': 'Rechnungsservices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='werkstatt.invoice')),
                ('stock_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lager.stockarticle')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.articletype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.manufacturer')),
            ],
            options={
                'verbose_name': 'Rechnungsartikel',
                'verbose_name_plural': 'Rechnungsartikel',
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_ebike', models.BooleanField(default=False, verbose_name='Ist E-Bike')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('bike_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modell')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Farbe')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seriennummer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='werkstatt.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Reparaturauftrag',
                'verbose_name_plural': 'Reparaturaufträge',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrderArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='werkstatt.repairorder', verbose_name='Reparaturauftrag')),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.stockarticle', verbose_name='Lagerartikel')),
            ],
            options={
                'verbose_name': 'Artikel im Reparaturauftrag',
                'verbose_name_plural': 'Artikel im Reparaturauftrag',
                'ordering': ['order', 'stock_article'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Anzahl')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='lager.article', verbose_name='Artikel')),
                ('repair_order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='werkstatt.repairorderarticle', verbose_name='Reparaturauftrag')),
            ],
            options={
                'verbose_name': 'Angeforderter Lagerartikel',
                'verbose_name_plural': 'Angeforderte Lagerartikel',
                'ordering': ['repair_order_article', 'article'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='werkstatt.repairorder', verbose_name='Reparaturauftrag')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service im Reparaturauftrag',
                'verbose_name_plural': 'Services im Reparaturauftrag',
                'ordering': ['order', 'service'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='werkstatt.servicecategory', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='StockArticleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Anzahl')),
                ('repair_order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='werkstatt.repairorderarticle', verbose_name='Reparaturauftrag')),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='lager.stockarticle', verbose_name='Lagerartikel')),
            ],
            options={
                'verbose_name': 'Reservierter Lagerartikel',
                'verbose_name_plural': 'Reservierte Lagerartikel',
                'ordering': ['repair_order_article', 'stock_article'],
            },
        ),
        migrations.AddConstraint(
            model_name='repairorderarticle',
            constraint=models.UniqueConstraint(fields=('order', 'stock_article'), name='unique_order_stock_article'),
        ),
        migrations.AddConstraint(
            model_name='articlerequest',
            constraint=models.UniqueConstraint(fields=('repair_order_article', 'article'), name='unique_roa_and_article'),
        ),
        migrations.AddConstraint(
            model_name='repairorderservice',
            constraint=models.UniqueConstraint(fields=('order', 'service'), name='unique_order_service'),
        ),
        migrations.AddConstraint(
            model_name='stockarticlereservation',
            constraint=models.UniqueConstraint(fields=('repair_order_article', 'stock_article'), name='unique_roa_and_sa'),
        ),
    ]
