# Generated by Django 5.1.3 on 2026-02-06 19:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal', models.CharField(max_length=5)),
                ('city', models.CharField(default='Nürnberg', max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('str_no', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('1', 'Auftragsannahme | Inspektion | Dienstleistung | Diverses'), ('2', 'Rahmen'), ('3', 'Räder | Bereifung'), ('4', 'Tretlager | Pedale | Antrieb'), ('5', 'Kettenschaltung | Nabenschaltung'), ('6', 'Bremsen'), ('7', 'Lichtanlage | Reflektoren'), ('8', 'E-Bike Sonderarbeiten')], max_length=100)),
                ('sub_category', models.CharField(blank=True, choices=[('1', 'Zubehörmontage'), ('2', 'Lenker | Vorbau '), ('3', 'Gabel | Lenkkopflager'), ('4', 'Gabelfederung'), ('5', 'Hinterbaufederung'), ('6', 'Sattel |Sattelstütze'), ('7', 'Gepäckträger |Rad- und Kettenschützer'), ('8', 'Vorderradnabe'), ('9', 'Hinterradnabe'), ('10', 'Pedale'), ('11', 'Kette'), ('12', 'Riemen'), ('13', 'Hydraulikbremse'), ('14', 'Scheibenbremse'), ('15', 'Software |Systemkontrolle | Fehler-Diagnose'), ('16', 'Instandsetzung')], max_length=100, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('children_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_gear', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('derailleur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('mtb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('road_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Received'), (9, 'Cancelled')], default=1)),
                ('submitted', models.DateField(blank=True, null=True)),
                ('delivered', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal', models.CharField(max_length=5)),
                ('city', models.CharField(default='Nürnberg', max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('str_no', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='werkstatt.articletype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateField()),
                ('postal', models.CharField(max_length=5)),
                ('city', models.CharField(default='Nürnberg', max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('str_no', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('bike_type', models.CharField(choices=[('children_bike', "Children's bike"), ('hub_gear', 'Hub Gear'), ('derailleur', 'Derailleur'), ('mtb', 'MTB'), ('road_bike', 'Road Bike')], default='derailleur', max_length=20)),
                ('bike_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('1', 'Auftragsannahme | Inspektion | Dienstleistung | Diverses'), ('2', 'Rahmen'), ('3', 'Räder | Bereifung'), ('4', 'Tretlager | Pedale | Antrieb'), ('5', 'Kettenschaltung | Nabenschaltung'), ('6', 'Bremsen'), ('7', 'Lichtanlage | Reflektoren'), ('8', 'E-Bike Sonderarbeiten')], max_length=100)),
                ('sub_category', models.CharField(blank=True, choices=[('1', 'Zubehörmontage'), ('2', 'Lenker | Vorbau '), ('3', 'Gabel | Lenkkopflager'), ('4', 'Gabelfederung'), ('5', 'Hinterbaufederung'), ('6', 'Sattel |Sattelstütze'), ('7', 'Gepäckträger |Rad- und Kettenschützer'), ('8', 'Vorderradnabe'), ('9', 'Hinterradnabe'), ('10', 'Pedale'), ('11', 'Kette'), ('12', 'Riemen'), ('13', 'Hydraulikbremse'), ('14', 'Scheibenbremse'), ('15', 'Software |Systemkontrolle | Fehler-Diagnose'), ('16', 'Instandsetzung')], max_length=100, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('children_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_gear', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('derailleur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('mtb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('road_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.invoice')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ean', models.CharField(max_length=13)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.invoice')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.articletype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.manufacturer')),
            ],
            options={
                'ordering': ['type', 'manufacturer', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ean', models.CharField(max_length=13)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.articletype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.manufacturer')),
            ],
            options={
                'ordering': ['type', 'manufacturer', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('bike_type', models.CharField(choices=[('children_bike', "Children's bike"), ('hub_gear', 'Hub Gear'), ('derailleur', 'Derailleur'), ('mtb', 'MTB'), ('road_bike', 'Road Bike')], default='derailleur', max_length=20)),
                ('bike_model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=30)),
                ('is_cargo_bike', models.BooleanField(default=False)),
                ('has_hub_engine', models.BooleanField(default=False)),
                ('has_mid_engine', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.customer')),
            ],
            options={
                'ordering': ['-date_finished', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Planned'), (2, 'Done')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='werkstatt.repairorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.service')),
            ],
        ),
        migrations.CreateModel(
            name='StockArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.article')),
            ],
        ),
        migrations.CreateModel(
            name='RepairOrderArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('installed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='werkstatt.repairorder')),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.stockarticle')),
            ],
        ),
        migrations.CreateModel(
            name='StockArticleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Reserved'), (2, 'Installed'), (3, 'Cancelled')], default=1)),
                ('repair_order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='werkstatt.repairorderarticle')),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='werkstatt.stockarticle')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='werkstatt.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='werkstatt.supplyorder')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderArticleReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_articles', to='werkstatt.supplyorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockArticleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_ordered', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repair_order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werkstatt.repairorderarticle')),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='werkstatt.stockarticle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repair_order_article', 'stock_article'), name='unique_request_per_roa')],
            },
        ),
    ]
