# Generated by Django 5.1.3 on 2026-02-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0002_alter_stockarticle_price'),
        ('werkstatt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicearticle',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.manufacturer'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lager.manufacturer', verbose_name='Hersteller'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
