# Generated by Django 5.1.3 on 2026-02-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkstatt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Nürnberg', max_length=50, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal',
            field=models.CharField(max_length=5, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='str_no',
            field=models.CharField(max_length=20, verbose_name='Nr.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='werkstatt.customer'),
        ),
    ]
