# Generated by Django 5.1.3 on 2026-02-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0006_remove_stockarticle_unique_article_price_and_more'),
        ('werkstatt', '0002_alter_customer_city_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicearticle',
            name='stock_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lager.stockarticle'),
        ),
    ]
