# Generated by Django 5.1.3 on 2026-02-07 18:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lieferung',
                'verbose_name_plural': 'Lieferungen',
                'ordering': ['delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('1', 'Auftragsannahme | Inspektion | Dienstleistung | Diverses'), ('2', 'Rahmen'), ('3', 'Räder | Bereifung'), ('4', 'Tretlager | Pedale | Antrieb'), ('5', 'Kettenschaltung | Nabenschaltung'), ('6', 'Bremsen'), ('7', 'Lichtanlage | Reflektoren'), ('8', 'E-Bike Sonderarbeiten')], max_length=100)),
                ('sub_category', models.CharField(blank=True, choices=[('1', 'Zubehörmontage'), ('2', 'Lenker | Vorbau'), ('3', 'Gabel | Lenkkopflager'), ('4', 'Gabelfederung'), ('5', 'Hinterbaufederung'), ('6', 'Sattel | Sattelstütze'), ('7', 'Gepäckträger | Rad- und Kettenschützer'), ('8', 'Vorderradnabe'), ('9', 'Hinterradnabe'), ('10', 'Pedale'), ('11', 'Kette'), ('12', 'Riemen'), ('13', 'Hydraulikbremse'), ('14', 'Scheibenbremse'), ('15', 'Software | Systemkontrolle | Fehler-Diagnose'), ('16', 'Instandsetzung')], max_length=100, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('children_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_gear', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('derailleur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mtb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('road_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_bike', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hub_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mid_engine', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('submitted', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschickt')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=100)),
                ('postal', models.CharField(max_length=5)),
                ('city', models.CharField(default='Nürnberg', max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('str_no', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Händler',
                'verbose_name_plural': 'Händler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lager.articletype', verbose_name='Übergeordneter Typ')),
            ],
            options={
                'verbose_name': 'Artikeltyp',
                'verbose_name_plural': 'Artikeltypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('ean', models.CharField(max_length=13, unique=True, verbose_name='EAN')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preis [VK]')),
                ('minimum', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.articletype', verbose_name='Typ')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.manufacturer', verbose_name='Hersteller')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.CreateModel(
            name='DeliveryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preis [EK]')),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='lager.article')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='lager.delivery')),
            ],
            options={
                'verbose_name': 'Lieferartikel',
                'verbose_name_plural': 'Lieferartikel',
            },
        ),
        migrations.CreateModel(
            name='StockArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_articles', to='lager.article', verbose_name='Lagerartikel')),
            ],
            options={
                'verbose_name': 'Lagerartikel',
                'verbose_name_plural': 'Lagerartikel',
                'ordering': ['article'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preis')),
                ('movement_type', models.PositiveSmallIntegerField(choices=[(1, 'Zugang'), (2, 'Abgang'), (3, 'Reserviert'), (4, 'Verwendet')])),
                ('reference', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lager.stockarticle')),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='lager.supplyorder'),
        ),
        migrations.CreateModel(
            name='SupplyOrderArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Menge')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preis [EK]')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.article', verbose_name='Artikel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='lager.supplyorder', verbose_name='Bestellung')),
            ],
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.vendor', verbose_name='Händler'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lager.vendor'),
        ),
        migrations.AddConstraint(
            model_name='stockarticle',
            constraint=models.UniqueConstraint(fields=('article', 'price'), name='unique_article_price'),
        ),
    ]
