# Generated by Django 5.1.3 on 2026-02-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'Lieferung', 'verbose_name_plural': 'Lieferungen'},
        ),
        migrations.AlterModelOptions(
            name='supplyorder',
            options={'ordering': ['-created'], 'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.RemoveField(
            model_name='supplyorder',
            name='submitted',
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='ordered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bestellt'),
        ),
        migrations.AlterField(
            model_name='deliveryarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='lager.article', verbose_name='Lieferartikel'),
        ),
        migrations.AlterField(
            model_name='deliveryarticle',
            name='checked_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eingelagert'),
        ),
        migrations.AlterField(
            model_name='deliveryarticle',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='lager.delivery', verbose_name='Lieferung'),
        ),
        migrations.AlterField(
            model_name='deliveryarticle',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Menge'),
        ),
    ]
