# Generated by Django 5.1.3 on 2026-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0002_alter_delivery_options_alter_supplyorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bestellnummer'),
        ),
    ]
