# Generated by Django 5.1.3 on 2026-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0003_supplyorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.CharField(max_length=50, unique=True, verbose_name='EAN'),
        ),
    ]
