# Generated by Django 5.1.3 on 2026-02-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0004_alter_article_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lager.articletype', verbose_name='Übergeordneter Typ'),
        ),
        migrations.AlterField(
            model_name='stockarticle',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
