# Generated by Django 5.1.3 on 2026-02-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0005_alter_articletype_parent_alter_stockarticle_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockarticle',
            name='unique_article_price',
        ),
        migrations.RemoveField(
            model_name='stockarticle',
            name='quantity',
        ),
    ]
