# Generated by Django 5.1.3 on 2026-02-15 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0006_remove_stockarticle_unique_article_price_and_more'),
        ('werkstatt', '0004_service_alter_repairorderservice_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='deliveryarticle',
            name='checked_in',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryarticle',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'IN | LIEFERUNG'), (2, 'OUT | LIEFERKORREKTUR'), (3, 'OUT | LIEFER-RETOUR'), (6, 'OUT | VERKAUFT'), (7, 'IN | RECHNUNG STORNIERT'), (8, 'OUT | AUSSCHUSS')]),
        ),
    ]
