# Generated by Django 5.1.3 on 2026-02-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0007_delete_service_remove_deliveryarticle_checked_in_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockarticle',
            constraint=models.UniqueConstraint(fields=('article', 'price'), name='unique_stock_article_price'),
        ),
    ]
