# Generated by Django 5.1.3 on 2026-02-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('werkstatt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Rejected'), (4, 'Done'), (5, 'Cancelled')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'New'), (2, 'Confirmed'), (3, 'Rejected'), (4, 'Done'), (5, 'Cancelled')], default=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('postal', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('str_nr', models.CharField(max_length=20)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='werkstatt.customer')),
            ],
        ),
    ]
